# filepath: /home/altair/sken_training_materials/mkdocs.yml
site_name: Sken 技術資料

nav:
  - ホーム画面: index.md 
  - 機械班:
      - SolidEdge: 
          - SolidEdge: training_materials/機械班/siryou.md
  - 電気班:
    - 講習資料:
      - ROS 2:
          - ROS2講習1: training_materials/講習資料/ROS 2/ROS2_1.md
          - ROS2講習2: training_materials/講習資料/ROS 2/ROS2_2.md
          - ROS2講習3: training_materials/講習資料/ROS 2/ROS2_3.md
          - ROS2講習ロボコン1: training_materials/講習資料/ROS 2/ROS2_ロボコン1.md
          - ROS2講習ロボコン2: training_materials/講習資料/ROS 2/ROS2_ロボコン2.md
      - python3:
          - 講習1: training_materials/講習資料/python3/python3講習1.md
          - 講習2: training_materials/講習資料/python3/python3講習2.md
          - 講習3: training_materials/講習資料/python3/python3講習3.md
      - 回路:
          - 回路講習0: training_materials/講習資料/回路/回路講習0.md
          - 回路講習1: training_materials/講習資料/回路/回路講習1スライド.md
          - 回路講習2: training_materials/講習資料/回路/回路講習2スライド.md
          - 回路講習3: training_materials/講習資料/回路/回路講習4.md
          - 回路講習4: training_materials/講習資料/回路/回路講習5.md
      - マイコン: 
          - マイコン講習_SystemWorkbench1: training_materials/講習資料/マイコンSW/マイコン1.md
          - マイコン講習_SystemWorkbench2: training_materials/講習資料/マイコンSW/マイコン2.md
          - マイコン講習_SystemWorkbench3: training_materials/講習資料/マイコンSW/マイコン3.md
      - 1年体験入部: training_materials/講習資料/1年体験入部/S-ken体験入部制御班Lちか.md
      - pid: training_materials/講習資料/pid/pid.md
      - ubuntu: training_materials/講習資料/ubuntu/ubuntu1.md
    - 講習課題:
      - python課題: training_materials/特訓課題/python.md
      - python課題答え: training_materials/講習資料/code/python答え.md
      - 回路課題: training_materials/特訓課題/回路.md
  - 共通資料:
    - マークダウン書き方: training_materials/講習資料/マークダウン書き方.md
    - ライセンス: training_materials/講習資料/ライセンス/ライセンススライド.md
    - Github: training_materials/講習資料/github/github1.md
  - 管理者連絡先: my.md 


theme:
  name: material
  font:
    text: Noto Sans JP
    code: Inconsolata
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/sken.jpeg
  favicon: images/sken.jpeg
  
extra:
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  consent:
    actions:
      - accept
      - manage
      - reject
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - header.autohide
    - navigation.tracking
  generator: false
  social:
    - icon: fontawesome/brands/square-x-twitter
      link: https://x.com/Flying___eagle
      name: mebiusbox2 on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/Altairu

copyright: "&copy; 2025 -Altair-"
repo_url: https://github.com/Altairu/sken_training_materials
repo_name: Altairu/sken_training_materials
markdown_extensions:
    - pymdownx.highlight
extra_javascript: 
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - admonition